baseURL = 'https://mehdi.carthages.org/'
languageCode = 'en-us'
summaryLength = 4
disableKinds = ["taxonomy"]

[params]
nowPage = "now"
failedPage = "failed"
blogPage = "blog"
favicon = false
externalLinks = [
    { name = "RRA Notion", url = "https://www.notion.so/templates/rapid-risk-assesment" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/%F0%9F%87%AB%F0%9F%87%B7-mehdi-khenissi-a88b54195/" }
]
socialLinks = [
    { name = "@MehdiKhen", url = "https://x.com/mehdikhen" },
    { name = "mehdi.khenissi@proton.me", url = "mailto:mehdi.khenissi@proton.me?subject=👋 Hi MK...&body=Hey Mehdi! I clearly clicked this link from your website. I wanted to say hi because..." }
]

title = "Hey, I’m Mehdi."
author = "Mehdi Khenissi"
initials = "MK"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"