baseURL = 'https://mehdi.carthages.org/'
languageCode = 'en-us'
summaryLength = 4
disableKinds = ["taxonomy"]

[params]
nowPage = "now"
failedPage = "failed"
blogPage = "blog"
favicon = false
externalLinks = [
    { name = "RRA Notion", url = "https://www.notion.so/templates/rapid-risk-assesment" },
    { name = "LinkedIn", url = "https://www.notion.so/templates/rapid-risk-assesment" }
]
socialLinks = [
    { name = "@MehdiKhen", url = "https://x.com/mehdikhen" },
    { name = "mehdi.khenissi@proton.me", url = "mailto:mehdi.khenissi@proton.me?subject=👋 Hi MK...&body=Hey Mehdi! I clearly clicked this link from your website. I wanted to say hi because..." }
]

title = "Hey, I’m Mehdi."
author = "Mehdi Khenissi"
description = "Your Description Here"
twitter_title = "Your Twitter Title"
twitter_image = "URL to your Twitter Image"
twitter_description = "Your Twitter Description"
twitter_site = "@YourTwitterHandle"
og_title = "Your OG Title"
og_image = "URL to your OG Image"
og_description = "Your OG Description"
og_site_name = "Your Site Name"
initials = "MK"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"